### ISSUE TITLE
It isn't allow to mutate arguments!

### ISSUE THREAD

**Issue by motifej** [davidkin/Request#1]
https://github.com/davidkin/Request/blob/8017e0aefcaf78401156490b1d9f47d53c58ec01/src/HttpRequest.js#L1

**Comment by davidkin** [comment]
We can not do this task without mutate arguments. Yeah, we can create another class, where we can create new XMLHttpRequest, but we lose our headers, because they belong to our old http object

**Comment by motifej** [comment]
ok, just to give the right name to 

> download
