### ISSUE TITLE
it is not clear, that function parseImg return URL

### ISSUE THREAD

**Issue by motifej** [davidkin/Request#11]
https://github.com/davidkin/Request/blob/8ff28fc3b420b1dd16587feac465d04c7968a941/src/progress.js#L31

**Comment by davidkin** [comment]
fixed

**Comment by davidkin** [comment]
rename function 'parseImg' to 'getImgUrl'
https://github.com/davidkin/Request/commit/f56a41ed8380bb015c97bfb3c81d00fd1c8bb135
