### ISSUE TITLE
keep work with DOM in one place and logic in another

### ISSUE THREAD

**Issue by motifej** [davidkin/Request#14]
https://github.com/davidkin/Request/blob/8ff28fc3b420b1dd16587feac465d04c7968a941/src/progress.js#L84

**Comment by davidkin** [comment]
realize logic in other file

**Comment by davidkin** [comment]
realize logic for server Work in file "requestsToServer.js"
https://github.com/davidkin/Request/commit/1194654386a41b8858667960864f109c3dbf4fb2#diff-eacf331f0ffc35d4b482f1d15a887d3bR108
