### ISSUE TITLE
Check how to use URL - https://developer.mozilla.org/ru/docs/Web/API/URL/URL

### ISSUE THREAD

**Issue by motifej** [davidkin/Request#2]
https://github.com/davidkin/Request/blob/8017e0aefcaf78401156490b1d9f47d53c58ec01/src/HttpRequest.js#L8

**Comment by davidkin** [comment]
I got it

**Comment by davidkin** [comment]
resolve this problem
https://github.com/davidkin/Request/commit/33f7badb4db5fb75338262231c8e1137590b1689
