### ISSUE TITLE
 code duplication

### ISSUE THREAD

**Issue by motifej** [davidkin/Request#3]
https://github.com/davidkin/Request/blob/8017e0aefcaf78401156490b1d9f47d53c58ec01/src/HttpRequest.js#L65

**Comment by davidkin** [comment]
fixed

**Comment by davidkin** [comment]
created function 'setMethod' where it fixed
75b5ae0

**Comment by davidkin** [comment]
rebuild code 
https://github.com/davidkin/Request/commit/cf9e5a1a295a4f7e8b5339610c9c795e1658950b
