### ISSUE TITLE
see line 123, for who i wrote it?

### ISSUE THREAD

**Issue by motifej** [davidkin/Request#5]
https://github.com/davidkin/Request/blob/8017e0aefcaf78401156490b1d9f47d53c58ec01/src/HttpRequest.js#L71

**Comment by davidkin** [comment]
i give one parametr to this function, when describe it in config
https://github.com/davidkin/Request/commit/1194654386a41b8858667960864f109c3dbf4fb2#diff-10fda37da79ad78a16e281037e1b2410R38
https://github.com/davidkin/Request/commit/1194654386a41b8858667960864f109c3dbf4fb2#diff-10fda37da79ad78a16e281037e1b2410R56
