### ISSUE TITLE
how developer can understand why transform function wasn't applied?

### ISSUE THREAD

**Issue by motifej** [davidkin/Request#6]
https://github.com/davidkin/Request/blob/8017e0aefcaf78401156490b1d9f47d53c58ec01/src/HttpRequest.js#L17

**Comment by davidkin** [comment]
dont't understand this issue

**Comment by davidkin** [comment]
add 'throw'

**Comment by davidkin** [comment]
add 'throw' in function
https://github.com/davidkin/Request/commit/f088ddbc8622f2e6dddc7116483d40156e39667d
