### ISSUE TITLE
what function parseImg do here?

### ISSUE THREAD

**Issue by motifej** [davidkin/Request#7]
https://github.com/davidkin/Request/blob/8017e0aefcaf78401156490b1d9f47d53c58ec01/src/progress.js#L31

**Comment by davidkin** [comment]
Function renamed to 'getUrlForImg'

**Comment by davidkin** [comment]
and replace to other file

**Comment by davidkin** [comment]
replace this file
https://github.com/davidkin/Request/commit/1194654386a41b8858667960864f109c3dbf4fb2#diff-10fda37da79ad78a16e281037e1b2410R25
