### ISSUE TITLE
this line looks too strange

### ISSUE THREAD

**Issue by motifej** [davidkin/Request#8]
https://github.com/davidkin/Request/blob/8ff28fc3b420b1dd16587feac465d04c7968a941/src/progress.js#L93

**Comment by davidkin** [comment]
fix it

**Comment by davidkin** [comment]
fixed this when realized new logix into another  file
https://github.com/davidkin/Request/commit/1194654386a41b8858667960864f109c3dbf4fb2#diff-10fda37da79ad78a16e281037e1b2410R38
https://github.com/davidkin/Request/commit/1194654386a41b8858667960864f109c3dbf4fb2#diff-10fda37da79ad78a16e281037e1b2410R56
