### ISSUE TITLE
 There will be a lot of calls to DOM

### ISSUE THREAD

**Issue by motifej** [davidkin/Request#9]
https://github.com/davidkin/Request/blob/8ff28fc3b420b1dd16587feac465d04c7968a941/src/progress.js#L3

**Comment by davidkin** [comment]
I did it for more detail view how file is uploading. I can apply 100% for progress status if it will be finish, but how it can do less calls if file will still upload
https://github.com/davidkin/Request/commit/e76a7c69ad1a15d81fa39cae47168e71007eb449

**Comment by davidkin** [comment]
I fill in progress on a 100% when the bytes loaded are equal toe bytes total  
https://github.com/davidkin/Request/commit/e76a7c69ad1a15d81fa39cae47168e71007eb449
